//authentication

export const POST_SIGN_IN = 'POST_SIGN_IN';
export const POST_SIGN_IN_SUCCESS = 'POST_SIGN_IN_SUCCESS';
export const POST_SIGN_IN_FAIL = 'POST_SIGN_IN_FAIL';

export const POST_CONFIRM = 'POST_CONFIRM';
export const POST_CONFIRM_SUCCESS = 'POST_CONFIRM_SUCCESS';
export const POST_CONFIRM_FAIL = 'POST_CONFIRM_FAIL';

export const POST_SIGN_UP = 'POST_SIGN_UP';
export const POST_SIGN_UP_SUCCESS = 'POST_SIGN_UP_SUCCESS';
export const POST_SIGN_UP_FAIL = 'POST_SIGN_UP_FAIL';

export const POST_ACTIVATION = 'POST_ACTIVATION';
export const POST_ACTIVATION_SUCCESS = 'POST_ACTIVATION_SUCCESS';
export const POST_ACTIVATION_FAIL = 'POST_ACTIVATION_FAIL';

export const POST_RESEND = 'POST_RESEND';
export const POST_RESEND_SUCCESS = 'POST_RESEND_SUCCESS';
export const POST_RESEND_FAIL = 'POST_RESEND_FAIL';

export const POST_RECOVER_FIRST_STEP = 'POST_RECOVER_FIRST_STEP';
export const POST_RECOVER_FIRST_STEP_SUCCESS = 'POST_RECOVER_FIRST_STEP_SUCCESS';
export const POST_RECOVER_FIRST_STEP_FAIL = 'POST_RECOVER_FIRST_STEP_FAIL';

export const POST_RECOVER_THIRD_STEP = 'POST_RECOVER_THIRD_STEP';
export const POST_RECOVER_THIRD_STEP_SUCCESS = 'POST_RECOVER_THIRD_STEP_SUCCESS';
export const POST_RECOVER_THIRD_STEP_FAIL = 'POST_RECOVER_THIRD_STEP_FAIL';

//user

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const PATCH_USER = 'PATCH_USER';
export const PATCH_USER_SUCCESS = 'PATCH_USER_SUCCESS';
export const PATCH_USER_FAIL = 'PATCH_USER_FAIL';

export const UPDATE_USER = 'UPDATE_USER';

//client

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL';

export const GET_CLIENT_DETAIL = 'GET_CLIENT_DETAIL';
export const GET_CLIENT_DETAIL_SUCCESS = 'GET_CLIENT_DETAIL_SUCCESS';
export const GET_CLIENT_DETAIL_FAIL = 'GET_CLIENT_DETAIL_FAIL';

export const POST_ADD_CLIENT = 'POST_ADD_CLIENT';
export const POST_ADD_CLIENT_SUCCESS = 'POST_ADD_CLIENT_SUCCESS';
export const POST_ADD_CLIENT_FAIL = 'POST_ADD_CLIENT_FAIL';

export const PATCH_EDIT_CLIENT = 'PATCH_EDIT_CLIENT';
export const PATCH_EDIT_CLIENT_SUCCESS = 'PATCH_EDIT_CLIENT_SUCCESS';
export const PATCH_EDIT_CLIENT_FAIL = 'PATCH_EDIT_CLIENT_FAIL';

export const POST_INVITE_CLIENT = 'POST_INVITE_CLIENT';
export const POST_INVITE_CLIENT_SUCCESS = 'POST_INVITE_CLIENT_SUCCESS';
export const POST_INVITE_CLIENT_FAIL = 'POST_INVITE_CLIENT_FAIL';

export const DELETE_CLIENT = 'DELETE_CLIENT';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';

export const UPDATE_CLIENT_DETAIL = 'UPDATE_CLIENT_DETAIL';

export const REMOVE_CLIENT = 'REMOVE_CLIENT';

//channels

export const GET_CHANNELS = 'GET_CHANNELS';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAIL = 'GET_CHANNELS_FAIL';

export const GET_CHANNEL_DETAIL = 'GET_CHANNEL_DETAIL';
export const GET_CHANNEL_DETAIL_SUCCESS = 'GET_CHANNEL_DETAIL_SUCCESS';
export const GET_CHANNEL_DETAIL_FAIL = 'GET_CHANNEL_DETAIL_FAIL';

export const POST_ADD_CHANNEL = 'POST_ADD_CHANNEL';
export const POST_ADD_CHANNEL_SUCCESS = 'POST_ADD_CHANNEL_SUCCESS';
export const POST_ADD_CHANNEL_FAIL = 'POST_ADD_CHANNEL_FAIL';

export const PATCH_EDIT_CHANNEL = 'PATCH_EDIT_CHANNEL';
export const PATCH_EDIT_CHANNEL_SUCCESS = 'PATCH_EDIT_CHANNEL_SUCCESS';
export const PATCH_EDIT_CHANNEL_FAIL = 'PATCH_EDIT_CHANNEL_FAIL';

export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';
export const DELETE_CHANNEL_FAIL = 'DELETE_CHANNEL_FAIL';

export const GET_INTERNAL_WALLETS = 'GET_INTERNAL_WALLETS';
export const GET_INTERNAL_WALLETS_SUCCESS = 'GET_INTERNAL_WALLETS_SUCCESS';
export const GET_INTERNAL_WALLETS_FAIL = 'GET_INTERNAL_WALLETS_FAIL';

export const GET_PLATFORMS = 'GET_PLATFORMS';
export const GET_PLATFORMS_SUCCESS = 'GET_PLATFORMS_SUCCESS';
export const GET_PLATFORMS_FAIL = 'GET_PLATFORMS_FAIL';

export const GET_CHANNEL_CHART = 'GET_CHANNEL_CHART';
export const GET_CHANNEL_CHART_SUCCESS = 'GET_CHANNEL_CHART_SUCCESS';
export const GET_CHANNEL_CHART_FAIL = 'GET_CHANNEL_CHART_FAIL';

export const GET_CHANNEL_ISSUES = 'GET_CHANNEL_ISSUES';
export const GET_CHANNEL_ISSUES_SUCCESS = 'GET_CHANNEL_ISSUES_SUCCESS';
export const GET_CHANNEL_ISSUES_FAIL = 'GET_CHANNEL_ISSUES_FAIL';

export const GET_CHANNEL_LOGS = 'GET_CHANNEL_LOGS';
export const GET_CHANNEL_LOGS_SUCCESS = 'GET_CHANNEL_LOGS_SUCCESS';
export const GET_CHANNEL_LOGS_FAIL = 'GET_CHANNEL_LOGS_FAIL';

export const GET_CHANNEL_POOL_SWITCHING = 'GET_CHANNEL_POOL_SWITCHING';
export const GET_CHANNEL_POOL_SWITCHING_SUCCESS = 'GET_CHANNEL_POOL_SWITCHING_SUCCESS';
export const GET_CHANNEL_POOL_SWITCHING_FAIL = 'GET_CHANNEL_POOL_SWITCHING_FAIL';

export const GET_RENT = 'GET_RENT';
export const GET_RENT_SUCCESS = 'GET_RENT_SUCCESS';
export const GET_RENT_FAIL = 'GET_RENT_FAIL';

export const GET_RENT_TRANSACTIONS = 'GET_RENT_TRANSACTIONS';
export const GET_RENT_TRANSACTIONS_SUCCESS = 'GET_RENT_TRANSACTIONS_SUCCESS';
export const GET_RENT_TRANSACTIONS_FAIL = 'GET_RENT_TRANSACTIONS_FAIL';

export const PATCH_SWITCH_RENT = 'PATCH_SWITCH_RENT';
export const PATCH_SWITCH_RENT_SUCCESS = 'PATCH_SWITCH_RENT_SUCCESS';
export const PATCH_SWITCH_RENT_FAIL = 'PATCH_SWITCH_RENT_FAIL';

export const GET_WTM_LIST = 'GET_WTM_LIST';
export const GET_WTM_LIST_SUCCESS = 'GET_WTM_LIST_SUCCESS';
export const GET_WTM_LIST_FAIL = 'GET_WTM_LIST_FAIL';

export const POST_CHANGE_EXTERNAL_WALLET = 'POST_CHANGE_EXTERNAL_WALLET';
export const POST_CHANGE_EXTERNAL_WALLET_SUCCESS = 'POST_CHANGE_EXTERNAL_WALLET_SUCCESS';
export const POST_CHANGE_EXTERNAL_WALLET_FAIL = 'POST_CHANGE_EXTERNAL_WALLET_FAIL';

export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';

export const UPDATE_CHANNEL_DETAIL = 'UPDATE_CHANNEL_DETAIL';

export const UPDATE_AUTO_SWITCH = 'UPDATE_AUTO_SWITCH';

export const UPDATE_RENT = 'UPDATE_RENT';

export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';

//pools

export const GET_POOLS = 'GET_POOLS';
export const GET_POOLS_SUCCESS = 'GET_POOLS_SUCCESS';
export const GET_POOLS_FAIL = 'GET_POOLS_FAIL';

export const GET_POOL_DETAIL = 'GET_POOL_DETAIL';
export const GET_POOL_DETAIL_SUCCESS = 'GET_POOL_DETAIL_SUCCESS';
export const GET_POOL_DETAIL_FAIL = 'GET_POOL_DETAIL_FAIL';

export const POST_ADD_POOL = 'POST_ADD_POOL';
export const POST_ADD_POOL_SUCCESS = 'POST_ADD_POOL_SUCCESS';
export const POST_ADD_POOL_FAIL = 'POST_ADD_POOL_FAIL';

export const PATCH_EDIT_POOL = 'PATCH_EDIT_POOL';
export const PATCH_EDIT_POOL_SUCCESS = 'PATCH_EDIT_POOL_SUCCESS';
export const PATCH_EDIT_POOL_FAIL = 'PATCH_EDIT_POOL_FAIL';

export const DELETE_POOL = 'DELETE_POOL';
export const DELETE_POOL_SUCCESS = 'DELETE_POOL_SUCCESS';
export const DELETE_POOL_FAIL = 'DELETE_POOL_FAIL';

export const GET_CURRENCIES_SYMBOLS = 'GET_CURRENCIES_SYMBOLS';
export const GET_CURRENCIES_SYMBOLS_SUCCESS = 'GET_CURRENCIES_SYMBOLS_SUCCESS';
export const GET_CURRENCIES_SYMBOLS_FAIL = 'GET_CURRENCIES_SYMBOLS_FAIL';

export const POST_VERIFY = 'POST_VERIFY';
export const POST_VERIFY_SUCCESS = 'POST_VERIFY_SUCCESS';
export const POST_VERIFY_FAIL = 'POST_VERIFY_FAIL';

export const UPDATE_POOL = 'UPDATE_POOL';

//workers

export const GET_WORKERS = 'GET_WORKERS';
export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';
export const GET_WORKERS_FAIL = 'GET_WORKERS_FAIL';

export const GET_WORKER_DETAIL = 'GET_WORKER_DETAIL';
export const GET_WORKER_DETAIL_SUCCESS = 'GET_WORKER_DETAIL_SUCCESS';
export const GET_WORKER_DETAIL_FAIL = 'GET_WORKER_DETAIL_FAIL';

export const GET_WORKER_CHART = 'GET_WORKER_CHART';
export const GET_WORKER_CHART_SUCCESS = 'GET_WORKER_CHART_SUCCESS';
export const GET_WORKER_CHART_FAIL = 'GET_WORKER_CHART_FAIL';

export const GET_MINER_CHART = 'GET_MINER_CHART';
export const GET_MINER_CHART_SUCCESS = 'GET_MINER_CHART_SUCCESS';
export const GET_MINER_CHART_FAIL = 'GET_MINER_CHART_FAIL';

//financial statistics

export const GET_FINANCIAL_TRANSACTIONS = 'GET_FINANCIAL_TRANSACTIONS';
export const GET_FINANCIAL_TRANSACTIONS_SUCCESS = 'GET_FINANCIAL_TRANSACTIONS_SUCCESS';
export const GET_FINANCIAL_TRANSACTIONS_FAIL = 'GET_FINANCIAL_TRANSACTIONS_FAIL';

export const GET_FINANCIAL_BILLING = 'GET_FINANCIAL_BILLING';
export const GET_FINANCIAL_BILLING_SUCCESS = 'GET_FINANCIAL_BILLING_SUCCESS';
export const GET_FINANCIAL_BILLING_FAIL = 'GET_FINANCIAL_BILLING_FAIL';

export const GET_CLIENTS_LIST = 'GET_CLIENTS_LIST';
export const GET_CLIENTS_LIST_SUCCESS = 'GET_CLIENTS_LIST_SUCCESS';
export const GET_CLIENTS_LIST_FAIL = 'GET_CLIENTS_LIST_FAIL';

export const GET_CHANNELS_LIST = 'GET_CHANNELS_LIST';
export const GET_CHANNELS_LIST_SUCCESS = 'GET_CHANNELS_LIST_SUCCESS';
export const GET_CHANNELS_LIST_FAIL = 'GET_CHANNELS_LIST_FAIL';